name: project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - scikit-learn 
  - python 3.10.12
  - jupyterlab
  - pandas
  - matplotlib.pyplot
C:\Users\tizmu\miniconda3\envs\dstoolbox
